server {
    listen 80;
    server_name eduportalsouthsudan.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name eduportalsouthsudan.org;

    location /static/ {
        proxy_pass http://127.0.0.1:5000/static/;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
    }
}
